// Shared v2 evidence logic: review gating, staleness, packet validation, and
// verified-only Table 8.3 aggregation. Imported by the browser workspace, the
// review scripts, and the tests so that every consumer applies the same rules.
// See docs/EVIDENCE_SCHEMA_V2.md.

export const DECISIONS = ["pending", "verified", "edited and verified", "rejected", "needs clarification"];
export const VERIFIED = new Set(["verified", "edited and verified"]);
export const REVIEW_FIELDS = ["review_decision", "reviewed_value", "reviewed_category", "reviewer", "reviewer_date", "reviewer_notes", "reviewed_evidence_fingerprint"];
export const CHAIN_FIELDS = ["sensor_technology", "sensor_location", "raw_acquired_signal", "physiological_parameter", "direct_vs_derived", "derived_reported_feature", "diagnostic_output"];
export const SUPPLEMENTARY_FIELDS = ["signal_access", "sampling_resolution", "continuity", "synchronization", "calibration", "validation_comparator", "processing_approach"];
export const VALUE_STATES = ["stated", "Not stated", "Not applicable", "Unreadable", ""];
export const FIELD_LABELS = {
  sensor_technology: "Physical sensor", sensor_location: "Sensor location", raw_acquired_signal: "Raw / acquired signal",
  physiological_parameter: "Physiological parameter", direct_vs_derived: "Directly sensed or derived",
  derived_reported_feature: "Derived / reported feature", diagnostic_output: "Diagnostic / report output",
  signal_access: "Raw signal retained / accessible", sampling_resolution: "Sampling / resolution", continuity: "Continuous vs episodic",
  synchronization: "Cross-channel synchronization", calibration: "Calibration", validation_comparator: "Validation / comparator",
  indications_for_use: "Indications for use", intended_use_role: "Intended-use role", processing_approach: "Processing approach (ML vs rule-based)", eligibility: "Study eligibility (IFU addresses OSA/SDB)",
};
export const RELATION_LABELS = {
  component_of: "is a component of", located_at: "is located at", acquires: "acquires", represents: "represents",
  measures: "measures", derivation: "derivation status", derived_feature_of: "is derived from", reported_as: "is reported from",
  generated_by: "is generated by",
};
export const BASIS_LABELS = {
  explicit: "Stated explicitly", "same-cell": "Same subject-column cell", "output-name": "Named in the output label",
  inferred: "Inferred — needs reviewer judgement", "not-stated": "Link not stated in source",
};

/** Is this record a claim (vs a relationship)? */
export const idOf = (item) => item.claim_id || item.relationship_id;

/** A review is stale when the evidence changed after the decision was recorded. */
export function isStale(item) {
  if (!item.review_decision || item.review_decision === "pending") return false;
  return !item.reviewed_evidence_fingerprint || item.reviewed_evidence_fingerprint !== item.evidence_fingerprint;
}

export function requiresNote(item) {
  return item.interpretation_v2 === "inferred" || item.basis === "inferred";
}

/** Validation of a proposed review record for one claim or relationship; returns error strings. */
export function reviewErrors(item, review = item) {
  const errors = [];
  const d = review.review_decision ?? "pending";
  if (!DECISIONS.includes(d)) errors.push(`invalid decision "${d}"`);
  if (d === "edited and verified" && !String(review.reviewed_value || "").trim() && !String(review.reviewed_category || "").trim())
    errors.push("“Edit and verify” needs a corrected value or category");
  if (d === "needs clarification" && !String(review.reviewer_notes || "").trim()) errors.push("“Needs clarification” needs a note describing the question");
  if (VERIFIED.has(d) && requiresNote(item) && !String(review.reviewer_notes || "").trim())
    errors.push("Verifying an inferred item needs a reviewer note explaining why the source supports it");
  if (VERIFIED.has(d) && item.basis === "not-stated")
    errors.push("A “link not stated” relationship cannot be verified as a link; reject it or mark it for clarification");
  return errors;
}

export const MACHINE_ACCEPTED = "machine-verified";

/**
 * Can this claim/relationship contribute to Table 8.3?
 * tier "human": only human verified / edited-and-verified, non-stale reviews.
 * tier "machine": a human decision always wins; otherwise an item counts only if the AI pipeline marked it
 * machine-verified, and never if it is inferred or a not-stated link.
 */
export function isCountable(item, tier = "human") {
  if (VERIFIED.has(item.review_decision)) return !isStale(item) && reviewErrors(item).length === 0;
  if (tier !== "machine" || (item.review_decision && item.review_decision !== "pending")) return false;
  if (item.machine_review?.status !== MACHINE_ACCEPTED) return false;
  return !requiresNote(item) && item.basis !== "not-stated";
}

export const effectiveValue = (c) => (c.review_decision === "edited and verified" && c.reviewed_value) ? c.reviewed_value : c.normalized_value;
export const effectiveCategory = (c) => (c.review_decision === "edited and verified" && c.reviewed_category) ? c.reviewed_category : (c.category || effectiveValue(c));

/** Overlay review records (packet or browser drafts) onto a v2 document without mutating it. */
export function applyReviews(doc, reviews = {}) {
  const pick = (x) => {
    const r = reviews[idOf(x)];
    if (!r) return x;
    const out = { ...x };
    for (const k of REVIEW_FIELDS) if (k in r) out[k] = r[k] ?? "";
    return out;
  };
  return { ...doc, claims: doc.claims.map(pick), relationships: doc.relationships.map(pick) };
}

export function reviewsFromPacket(packet) {
  const out = {};
  for (const r of [...(packet.claims || []), ...(packet.relationships || [])]) {
    out[idOf(r)] = Object.fromEntries(REVIEW_FIELDS.map((k) => [k, r[k] ?? ""]));
  }
  return out;
}

// ---------------------------------------------------------------- packets

const PACKET_CLAIM_KEYS = ["claim_id", "k_number", "family_id", "field", "chain_ids", "value_state", "polarity", "normalized_value", "category",
  "source_value", "interpretation_v2", "subject_scope", "page", "primary_quote", "evidence_fingerprint", "origin"];
const PACKET_REL_KEYS = ["relationship_id", "k_number", "chain_id", "from_claim_id", "relation", "to_claim_id", "basis", "note", "evidence_fingerprint"];

export function buildPacket(docs, generatedAt = new Date().toISOString()) {
  const claims = [], relationships = [];
  for (const doc of docs) {
    const chainIds = {};
    for (const ch of doc.chains) for (const slot of Object.values(ch.slots)) for (const id of slot.claim_ids) (chainIds[id] ||= new Set()).add(ch.chain_id);
    for (const c of doc.claims) {
      const primary = c.evidence?.find((a) => a.role === "primary") || c.evidence?.[0];
      const row = { ...Object.fromEntries(PACKET_CLAIM_KEYS.map((k) => [k, c[k] ?? ""])),
        chain_ids: [...(chainIds[c.claim_id] || [])].sort(), page: primary?.page ?? c.page ?? "", primary_quote: primary?.exact_quote ?? c.supporting_excerpt ?? "" };
      for (const k of REVIEW_FIELDS) row[k] = c[k] ?? "";
      claims.push(row);
    }
    for (const r of doc.relationships) {
      const row = Object.fromEntries(PACKET_REL_KEYS.map((k) => [k, r[k] ?? ""]));
      for (const k of REVIEW_FIELDS) row[k] = r[k] ?? "";
      relationships.push(row);
    }
  }
  return { schema_version: "2.0-prototype", packet_type: "evidence-review-v2", generated_at_utc: generatedAt,
    k_numbers: docs.map((d) => d.document.k_number), allowed_review_decisions: DECISIONS, review_fields: REVIEW_FIELDS,
    rule: "Only review fields may change. IDs, values, and evidence fingerprints are checked against the canonical packet.",
    claims, relationships };
}

/**
 * Validate an incoming packet (browser export, JSON edit, or workbook import) against the canonical packet.
 * Returns {errors, updates} where updates maps id → review fields that changed.
 */
export function validateIncoming(canonical, incoming, { requireComplete = false } = {}) {
  const errors = [];
  const updates = {};
  const canon = new Map([...canonical.claims, ...canonical.relationships].map((x) => [idOf(x), x]));
  const seen = new Set();
  for (const row of [...(incoming.claims || []), ...(incoming.relationships || [])]) {
    const id = idOf(row);
    if (!id) { errors.push("row without claim_id/relationship_id"); continue; }
    if (seen.has(id)) errors.push(`${id}: duplicated`);
    seen.add(id);
    const base = canon.get(id);
    if (!base) { errors.push(`${id}: unknown ID (IDs are stable and cannot be created by a review packet)`); continue; }
    if (row.evidence_fingerprint && row.evidence_fingerprint !== base.evidence_fingerprint)
      errors.push(`${id}: reviewed against different evidence (fingerprint ${row.evidence_fingerprint} ≠ ${base.evidence_fingerprint})`);
    for (const k of ["normalized_value", "field", "relation", "basis"]) if (k in row && row[k] !== "" && base[k] !== undefined && String(row[k]) !== String(base[k]))
      errors.push(`${id}: ${k} changed ("${base[k]}" → "${row[k]}"); edit the value through reviewed_value instead`);
    const review = Object.fromEntries(REVIEW_FIELDS.map((k) => [k, row[k] ?? base[k] ?? ""]));
    review.review_decision ||= "pending";
    for (const e of reviewErrors(base, review)) errors.push(`${id}: ${e}`);
    if (review.review_decision !== "pending" && !review.reviewed_evidence_fingerprint) review.reviewed_evidence_fingerprint = base.evidence_fingerprint;
    if (review.review_decision === "pending") review.reviewed_evidence_fingerprint = "";
    const changed = REVIEW_FIELDS.filter((k) => String(review[k] ?? "") !== String(base[k] ?? ""));
    if (changed.length) updates[id] = review;
  }
  if (requireComplete) for (const id of canon.keys()) if (!seen.has(id)) errors.push(`${id}: missing from incoming packet`);
  return { errors, updates };
}

export function mergePacket(canonical, updates) {
  const apply = (x) => (updates[idOf(x)] ? { ...x, ...updates[idOf(x)] } : x);
  return { ...canonical, claims: canonical.claims.map(apply), relationships: canonical.relationships.map(apply) };
}

// ---------------------------------------------------------------- Table 8.3

/**
 * Verified-only Table 8.3 (cumulative FDA measurement inventory):
 * physiological parameter × sensor type, with sensor locations, raw signals, derivation, and derived/reported features.
 * A value enters only if its claim is countable AND it is connected to a countable parameter claim through countable,
 * stated relationships within the same chain. Verified "Not stated" entries are counted as "Not specified".
 * Clearance (K-number) and device-family counts are kept separate.
 */
export function buildTable83(docs, { tier = "human", requireEligibility = false } = {}) {
  const rows = new Map();
  const excluded = [];
  const bucket = () => ({ clearances: new Set(), families: new Set() });
  const tally = (map, label, doc) => {
    const b = map.get(label) || bucket();
    b.clearances.add(doc.document.k_number);
    if (doc.document.family_id) b.families.add(doc.document.family_id);
    map.set(label, b);
  };
  const counted = (x) => isCountable(x, tier);
  const eligibility = [];
  for (const doc of docs) {
    const byId = new Map(doc.claims.map((c) => [c.claim_id, c]));
    if (requireEligibility) {
      const e = doc.claims.find((c) => c.field === "eligibility" && counted(c));
      eligibility.push({ k_number: doc.document.k_number, status: e ? effectiveValue(e) : "not established" });
      if (!e || effectiveValue(e) !== "Eligible") {
        excluded.push({ k_number: doc.document.k_number, chain_id: "*", reason: e ? "not eligible (IFU does not address OSA/SDB)" : "eligibility not established" });
        continue;
      }
    }
    for (const chain of doc.chains) {
      if (chain.kind === "report") continue;
      const rels = doc.relationships.filter((r) => r.chain_id === chain.chain_id && counted(r) && r.basis !== "not-stated");
      const params = (chain.slots.physiological_parameter?.claim_ids || []).map((id) => byId.get(id))
        .filter((c) => c && c.value_state === "stated" && counted(c));
      if (!params.length) {
        excluded.push({ k_number: doc.document.k_number, chain_id: chain.chain_id, reason: "no verified physiological parameter" });
        continue;
      }
      for (const param of params) {
        const reach = new Set([param.claim_id]);
        let grew = true;
        while (grew) {
          grew = false;
          for (const r of rels) {
            const a = byId.get(r.from_claim_id), b = byId.get(r.to_claim_id);
            if (!a || !b || !counted(a) || !counted(b)) continue;
            if (reach.has(r.from_claim_id) !== reach.has(r.to_claim_id)) { reach.add(r.from_claim_id); reach.add(r.to_claim_id); grew = true; }
          }
        }
        const slotClaims = (field) => (chain.slots[field]?.claim_ids || []).map((id) => byId.get(id)).filter((c) => c && counted(c) && c.aggregate !== false);
        const linked = (field) => slotClaims(field).filter((c) => reach.has(c.claim_id) && c.value_state === "stated");
        const gap = (field) => slotClaims(field).filter((c) => c.value_state === "Not stated");
        const values = (field) => {
          const l = linked(field);
          if (l.length) return l.filter((c) => c.polarity !== "negated").map(effectiveCategory);
          return [...new Set(gap(field).map((c) => c.category || "Not specified"))];
        };
        const paramLabel = effectiveCategory(param);
        const row = rows.get(paramLabel) || { parameter: paramLabel, ...bucket(), sensors: new Map() };
        row.clearances.add(doc.document.k_number);
        if (doc.document.family_id) row.families.add(doc.document.family_id);
        let sensorTypes = values("sensor_technology");
        if (!sensorTypes.length) sensorTypes = ["(sensor link not verified)"];
        for (const st of sensorTypes) {
          const sub = row.sensors.get(st) || { sensor_type: st, ...bucket(), locations: new Map(), raw_signals: new Map(), derivation: new Map(), features: new Map(), exclusions: new Map(), records: [] };
          sub.clearances.add(doc.document.k_number);
          if (doc.document.family_id) sub.families.add(doc.document.family_id);
          for (const v of values("sensor_location")) tally(sub.locations, v, doc);
          for (const v of values("raw_acquired_signal")) tally(sub.raw_signals, v, doc);
          for (const v of values("direct_vs_derived")) tally(sub.derivation, v, doc);
          for (const f of ["derived_reported_feature", "diagnostic_output"]) {
            for (const c of linked(f)) tally(c.polarity === "negated" ? sub.exclusions : sub.features, effectiveCategory(c), doc);
          }
          sub.records.push({ k_number: doc.document.k_number, family_id: doc.document.family_id, chain_id: chain.chain_id, parameter_claim_id: param.claim_id,
            claim_ids: [...reach].sort() });
          row.sensors.set(st, sub);
        }
        rows.set(paramLabel, row);
      }
    }
  }
  const counts = (map) => [...map.entries()].map(([label, b]) => ({ label, clearances: b.clearances.size, families: b.families.size, k_numbers: [...b.clearances].sort() }))
    .sort((a, b) => b.clearances - a.clearances || a.label.localeCompare(b.label));
  return {
    tier,
    rule: tier === "machine"
      ? "Human-verified or AI machine-verified (independent double extraction + adversarial verification) claims connected through equally accepted stated relationships; inferred items and not-stated links excluded; human decisions override. Clearance and family counts are separate."
      : "Verified and edited-and-verified, non-stale claims connected through verified stated relationships only. Clearance and family counts are separate.",
    eligibility,
    rows: [...rows.values()].map((r) => ({
      parameter: r.parameter, clearances: r.clearances.size, families: r.families.size, k_numbers: [...r.clearances].sort(),
      sensors: [...r.sensors.values()].map((s) => ({ sensor_type: s.sensor_type, clearances: s.clearances.size, families: s.families.size,
        k_numbers: [...s.clearances].sort(), locations: counts(s.locations), raw_signals: counts(s.raw_signals), derivation: counts(s.derivation),
        features: counts(s.features), exclusions: counts(s.exclusions), records: s.records })),
    })).sort((a, b) => b.clearances - a.clearances || a.parameter.localeCompare(b.parameter)),
    excluded_chains: excluded,
  };
}

/** Per-document review progress used by the workspace header. */
export function progress(doc) {
  // (machine-review counts are reported separately by machineProgress)
  const items = [...doc.claims, ...doc.relationships];
  const by = Object.fromEntries(DECISIONS.map((d) => [d, 0]));
  let stale = 0;
  for (const x of items) { by[x.review_decision || "pending"]++; if (isStale(x)) stale++; }
  return { total: items.length, claims: doc.claims.length, relationships: doc.relationships.length, by, stale,
    countable: items.filter(isCountable).length };
}

export function machineProgress(doc) {
  const items = [...doc.claims, ...doc.relationships].filter((x) => x.machine_review);
  const by = {};
  for (const x of items) by[x.machine_review.status] = (by[x.machine_review.status] || 0) + 1;
  return { total: items.length, by };
}
