"""Authoring source for pipeline/curation/K143272.json. Run: python3 pipeline/curation/author_K143272.py pipeline/curation/K143272.json"""
import json, sys

SUBJ = lambda row: {"table_row": row, "col": "subject"}
COMM = lambda row: {"table_row": row, "col": "comment"}
LABEL = lambda row: {"table_row": row, "col": "characteristic"}
SEC = lambda s: {"section": s}
IFU_OCR = {"page": 3, "block_type": "ocr_text"}
INDICES = "Analysis result (Indices)"

def ev(quote, where, role="primary", value=None, note=None):
    d = {"quote": quote, "in": where, "role": role}
    if value: d["value"] = value
    if note: d["note"] = note
    return d

IFU_TEXT = ("The ApneaLink™ Air device is indicated for use by Health Care Professionals (HCP), where it may aid "
            "in the diagnosis of sleep disordered breathing for adult patients. ApneaLink Air records the following "
            "data: patient respiratory nasal airflow, snoring, blood oxygen saturation, pulse, respiratory effort and "
            "body position during sleep. The device uses these recordings to produce a report for the HCP that may aid "
            "in the diagnosis of sleep disordered breathing or for further clinical investigation. The device is "
            "intended for home and hospital use under the direction of a HCP.")
CH_FLOW = "flow channel for measurement of patient respiratory nasal pressure."
CH_OX = "oximeter input to measure degree of oxygen saturation of the blood and pulse rate."
CH_EFF = "effort channel to measure the respiratory effort using a pneumatic principle."
CH_POS = "body position channel to determine body position of the patient during sleep"
ST_PRESS = "Utilizes solid-state pressure sensor for nasal flow and effort that converts pressure changes to electrical signal levels"
ANGLE = "The ApneaLink Air device shows similar to the Nox T3 body position information according to the angle the device is tilted or rotated."
IDX_LEAD = "The following indices are generated from the ApneaLink Software:"
IN_REPORT = "Thus the indices generated from the ApneaLink Software in the report remain unchanged."
EDF_ALL = ("Recorded data is stored in European Data Format (EDF+) file on SD card. When device is connected to PC via USB "
           "the device provides access to its internal memory as mass storage memory including the recorded EDF+ files.")
POS_EDF = "The body position data is stored as an EDF+ file on the recorder. It is accessible on a computer via USB connection using an EDF viewer."
POS_NOT_REPORT = "Data is neither part of the report generated by ApneaLink Software nor does it influence or alter any index of the report."

claims = []
def claim(ref, field, value, source="", interp="explicit", state="stated", evidence=(), category="", note="",
          polarity="affirmed", absence=None, aggregate=True, aggregate_note=None):
    c = {"ref": ref, "field": field, "source_value": source, "normalized_value": value, "value_state": state,
         "interpretation": interp, "polarity": polarity, "category": category, "note": note, "evidence": list(evidence)}
    if absence: c["absence_terms"] = absence
    if not aggregate:
        c["aggregate"] = False
        c["aggregate_note"] = aggregate_note or ""
    claims.append(c)

assess = []
def legacy(cid, ref, verdict, action, note, evidence=(), interp="explicit", category="", superseded=(), suggested=None,
           aggregate=True, aggregate_note=None, polarity="affirmed"):
    a = {"claim_id": cid, "ref": ref, "verdict": verdict, "recommended_action": action, "note": note,
         "interpretation": interp, "category": category, "polarity": polarity, "evidence": list(evidence),
         "superseded_by": list(superseded)}
    if suggested: a["suggested_reviewed_value"] = suggested
    if not aggregate:
        a["aggregate"] = False
        a["aggregate_note"] = aggregate_note or ""
    assess.append(a)

# ------------------------------------------------------------------ intended use
legacy("CLM-5f420010811a", "iu.ifu", "supported", "verify",
       "Verbatim match with the 510(k) Summary Intended Use section. The same text appears on the image-only Form FDA 3881 (p. 3), available only as local OCR.",
       [ev(IFU_TEXT, SEC("Intended Use")),
        ev("ApneaLink Air records the following data: patient respiratory nasal airflow, snoring, blood oxygen saturation, pulse, respiratory effort and body position during sleep.", IFU_OCR, "context", note="Form FDA 3881, local OCR (unreviewed)")],
       aggregate=False, aggregate_note="Indications text is not a Table 8.3 measurement field.")
legacy("CLM-69b71b898d7c", "iu.role", "supported", "verify",
       "Source wording 'may aid in the diagnosis' normalized to 'aid to diagnosis'.",
       [ev("where it may aid in the diagnosis of sleep disordered breathing for adult patients", SEC("Intended Use"), value="aid in the diagnosis")],
       interp="normalized", aggregate=False, aggregate_note="Intended-use role is not a Table 8.3 measurement field.")
legacy("CLM-39b492a99694", "iu.role2", "unsupported", "reject",
       "Duplicate of CLM-69b71b898d7c with the value 'evaluation', which the source does not use. The source says 'aid in the diagnosis'.",
       [ev("where it may aid in the diagnosis of sleep disordered breathing for adult patients", SEC("Intended Use"), "context")],
       interp="contradicted", superseded=["iu.role"], aggregate=False)

# ------------------------------------------------------------------ airflow chain
claim("np.cannula", "sensor_technology", "Nasal cannula with plastic tubing (pressure-sensing patient interface)",
      "Plastic tubing and cannula for pressure sensing",
      evidence=[ev("Plastic tubing and cannula for pressure sensing", SUBJ("Method of connection to the Patient"), value="cannula for pressure sensing"),
                ev("The disposable plastic nasal cannula is connected to the ApneaLink Air recorder and fixed at the patient’s nose.", SEC("Device Description"), "context")],
      note="Patient interface, not the transducer. Recorded as a component so that its location is not transferred to the pressure sensor.",
      aggregate=False, aggregate_note="Component of the nasal-pressure sensing system; the Table 8.3 sensor type is taken from the transducer claim.")
legacy("CLM-006338992a5c", "np.sensor", "supported", "verify",
       "Subject-column Sensor Technology cell. The same sensor type is stated 'for nasal flow and effort'; how many physical sensors there are is not stated.",
       [ev(ST_PRESS, SUBJ("Sensor Technology"), value="solid-state pressure sensor")],
       category="Nasal pressure transducer")
legacy("CLM-9feb9ae5aa69", "np.loc", "supported, wrong evidence; value compounds component and location", "edit and verify",
       "The legacy excerpt (the Sensor Technology cell) does not mention a location. Re-anchored to the Device Description. The location belongs to the nasal cannula, not to the solid-state pressure sensor.",
       [ev("The disposable plastic nasal cannula is connected to the ApneaLink Air recorder and fixed at the patient’s nose.", SEC("Device Description"), value="patient’s nose")],
       category="Nares / nasal cannula", suggested="Patient’s nose (nasal cannula)")
claim("np.sensorloc", "sensor_location", "Not stated", state="Not stated", interp="not stated",
      evidence=[ev("The disposable plastic nasal cannula is connected to the ApneaLink Air recorder and fixed at the patient’s nose.", SEC("Device Description"), "context")],
      note="Where the solid-state pressure sensor sits (for example, inside the recorder) is not stated. Only the cannula’s connection to the recorder is stated.",
      aggregate=False, aggregate_note="Transducer location gap; the Table 8.3 location for this chain comes from the cannula.")
legacy("CLM-fb528aac2fe3", "np.raw", "supported, evidence re-anchored", "verify",
       "The legacy excerpt did not contain 'nasal pressure'. Re-anchored to the subject-column Channels cell. The source does not describe the signal as a waveform.",
       [ev(CH_FLOW, SUBJ("Channels"), value="respiratory nasal pressure"),
        ev("that converts pressure changes to electrical signal levels", SUBJ("Sensor Technology"), "context")],
       category="Nasal pressure signal (waveform not specified)")
legacy("CLM-b7527e172867", "np.param", "supported, evidence re-anchored", "verify",
       "Re-anchored to the Intended Use wording. The comparison table states that pressure values are transformed into flow values in the recorder.",
       [ev("patient respiratory nasal airflow", SEC("Intended Use"), value="respiratory nasal airflow"),
        ev("Location of linearization (Transformation of pressure values in flow values)", LABEL("Location of linearization (Transformation of pressure values in flow values)"), "context")],
       category="Airflow / respiration")
claim("np.direct", "direct_vs_derived", "Derived: nasal pressure values are transformed (linearized) into flow values in the ApneaLink Air recorder",
      "Transformation of pressure values in flow values",
      evidence=[ev("ApneaLink Air recorder", SUBJ("Location of linearization (Transformation of pressure values in flow values)")),
                ev("Location of linearization (Transformation of pressure values in flow values)", LABEL("Location of linearization (Transformation of pressure values in flow values)"), "primary", value="Transformation of pressure values in flow values")],
      interp="normalized", category="Derived",
      note="Airflow is not sensed directly: the row states where pressure is transformed into flow. The linearization algorithm is not described.")

# ------------------------------------------------------------------ effort chain
claim("eff.sensor", "sensor_technology", "Pneumatic respiratory effort sensor (solid-state pressure sensor)", "effort channel ... using a pneumatic principle",
      evidence=[ev(CH_EFF, SUBJ("Channels"), value="pneumatic principle"),
                ev(ST_PRESS, SUBJ("Sensor Technology"), "context"),
                ev("The respiratory effort sensor is connected to the ApneaLink Air recorder and held in place by the belt.", SEC("Device Description"), "context")],
      interp="normalized", category="Pneumatic effort sensor",
      note="Not RIP: 'RIP technology' appears only in the Nox T3 predicate column. The transducer type comes from the shared Sensor Technology cell ('for nasal flow and effort').")
legacy("CLM-25cea7da6112", "eff.sensor.legacy", "contradicted (predicate column)", "reject",
       "'Respiratory Effort Sensors (RIP technology)' appears only in the Nox T3 predicate column. The subject column says the effort channel uses 'a pneumatic principle'.",
       [ev("Respiratory Effort Sensors (RIP technology)", {"table_row": "Sensor Technology", "col": "predicate"}, "limiting", note="Predicate (Nox T3) column. Not evidence for the subject device."),
        ev(CH_EFF, SUBJ("Channels"), "limiting")],
       interp="contradicted", superseded=["eff.sensor"], aggregate=False)
legacy("CLM-64a1213f973f", "eff.loc", "supported, evidence re-anchored", "verify",
       "The legacy excerpt (the Channels cell) did not mention a location. Re-anchored to the Device Description.",
       [ev("The ApneaLink Air recorder and the respiratory effort sensor must be fastened with the re-usable belt on the patient’s chest parallel to the spine.", SEC("Device Description"), value="patient’s chest parallel to the spine"),
        ev("elastic cloth material belt to support unit and the respiratory effort sensor", SUBJ("Method of connection to the Patient"), "context")],
       category="Chest")
claim("eff.raw", "raw_acquired_signal", "Pressure changes from the pneumatic effort sensor, converted to electrical signal levels",
      "converts pressure changes to electrical signal levels",
      evidence=[ev(ST_PRESS, SUBJ("Sensor Technology"), value="converts pressure changes to electrical signal levels"),
                ev(CH_EFF, SUBJ("Channels"), "context")],
      interp="normalized", category="Pneumatic pressure signal (waveform not specified)",
      note="Normalized from the shared pressure-sensor description. Not described as a waveform. No calibration or units are stated.")
legacy("CLM-e36feb851fad", "eff.raw.legacy", "misclassified", "reject",
       "'Respiratory effort' is the physiological parameter, not the acquired signal.",
       [ev(CH_EFF, SUBJ("Channels"), "context")], interp="contradicted", superseded=["eff.raw"], aggregate=False)
legacy("CLM-cb110eefecb7", "eff.param", "supported", "verify",
       "Subject-column Channels cell and Intended Use.",
       [ev(CH_EFF, SUBJ("Channels"), value="respiratory effort"),
        ev("respiratory effort and body position during sleep", SEC("Intended Use"), "context")],
       category="Respiratory effort")
legacy("CLM-0924252480a1", "eff.direct", "supported with limitation", "verify",
       "Source verb is 'measure'. Calibration, units, and quantitative effort are not stated; do not interpret as calibrated effort.",
       [ev(CH_EFF, SUBJ("Channels"), value="measure")],
       interp="normalized", category="Directly sensed")
claim("eff.calib", "calibration", "Not stated", state="Not stated", interp="not stated",
      absence=["calibrat", "quantitativ", "amplitude"],
      note="No calibration or quantitative effort output is described for the effort channel.")

# ------------------------------------------------------------------ oximetry (SpO2 + pulse)
legacy("CLM-73e2718fb82d", "ox.sensor", "supported, evidence re-anchored", "verify",
       "Re-anchored to the subject-column Sensor Technology cell. The optical method (transmission or reflectance PPG) is not stated.",
       [ev("Utilizes oximetry sensor", SUBJ("Sensor Technology"), value="oximetry sensor"),
        ev("The oximetry sensor is connected to the Xpod and fixed at the patient’s finger.", SEC("Device Description"), "context")],
       category="Oximetry sensor, technology unspecified")
claim("ox.module", "sensor_technology", "Pulse oximeter module: Nonin Xpod 3012 LP (low-power Xpod)", "Nonin Xpod 3012 LP",
      evidence=[ev("Nonin Xpod 3012 LP", SUBJ("Xpod oximeter"), value="Nonin Xpod 3012 LP"),
                ev("Low power Xpod replaces previous Xpod model.", SEC("Technology"), "context")],
      aggregate=False, aggregate_note="Signal-processing module; the Table 8.3 sensor type is taken from the oximetry sensor.")
legacy("CLM-bf8541d0dc67", "ox.loc", "supported", "verify", "The excerpt states the location explicitly.",
       [ev("The oximetry sensor is connected to the Xpod and fixed at the patient’s finger.", SEC("Device Description"), value="patient’s finger"),
        ev("Flexi Wrap to fix the oximeter sensor to the patient’s finger.", SUBJ("Method of connection to the Patient"), "context")],
       category="Finger")
claim("ox.modloc", "sensor_location", "Xpod module fixed at the belt via clip", "fixed at the belt via clip",
      evidence=[ev("The new low power Xpod is fixed at the belt via clip.", SUBJ("Method of connection to the Patient"), value="fixed at the belt via clip")],
      aggregate=False, aggregate_note="Module location, not a sensor location.")
claim("ox.raw", "raw_acquired_signal", "Not stated", state="Not stated", interp="not stated",
      absence=["photopleth", "plethysmo", "PPG", "pleth", "waveform", "infrared", "optical", "absorb"],
      evidence=[ev(CH_OX, SUBJ("Channels"), "context")],
      category="Not specified",
      note="The summary does not describe the optical signal the oximeter acquires. Do not infer a PPG waveform from SpO2 or pulse rate.")
legacy("CLM-b02ad0500a1b", "ox.raw.legacy", "misclassified, not atomic", "reject",
       "Oxygen saturation and pulse rate are physiological parameters, not the acquired signal. Two parameters are combined in one value.",
       [ev(CH_OX, SUBJ("Channels"), "context")], interp="contradicted", superseded=["ox.raw", "ox.param", "pr.param"], aggregate=False)
claim("ox.param", "physiological_parameter", "Blood oxygen saturation (SpO2)", "oxygen saturation of the blood",
      evidence=[ev(CH_OX, SUBJ("Channels"), value="oxygen saturation of the blood"),
                ev("blood oxygen saturation", SEC("Intended Use"), "context")],
      category="Oxygen saturation")
claim("pr.param", "physiological_parameter", "Pulse rate", "pulse rate",
      evidence=[ev(CH_OX, SUBJ("Channels"), value="pulse rate"),
                ev("blood oxygen saturation, pulse, respiratory effort", SEC("Intended Use"), "context")],
      category="Cardiac activity / heart rate")
legacy("CLM-f706d25f6cda", "ox.param.legacy", "not atomic", "reject",
       "Combines two parameters. Superseded by separate SpO2 and pulse-rate claims.",
       [ev(CH_OX, SUBJ("Channels"), "context")], interp="normalized", superseded=["ox.param", "pr.param"], aggregate=False)
legacy("CLM-eca11ab54826", "ox.direct", "supported with limitation, evidence re-anchored", "verify",
       "The legacy excerpt (the location sentence) did not support 'measured'. Re-anchored to the Channels cell. The measurement method is not described.",
       [ev(CH_OX, SUBJ("Channels"), value="measure")], interp="normalized", category="Directly sensed")
claim("ox.valid", "validation_comparator", "Low-power Xpod stated to have the same accuracy and performance as the previous Xpod; test method and comparator not stated",
      "Same accuracy and performance as the existing Xpod",
      evidence=[ev("Same accuracy and performance as the existing Xpod, but considerably lower power draw.", SEC("Technology")),
                ev("Xpod 3012 and Xpod 3012 LP have equivalent performance and clinical accuracy.", COMM("Xpod oximeter"), "context")],
      interp="normalized")

# ------------------------------------------------------------------ body position
legacy("CLM-5db33eba2fd1", "pos.sensor", "supported, wrong evidence (predicate column)", "verify",
       "The legacy excerpt quoted the Nox T3 predicate column ('Solid state position/activity sensor'). Re-anchored to the subject column, which continues across pages 9–10. The sensing technology (for example, an accelerometer) is not stated.",
       [ev("Utilizes solid-state actigraphy sensor for position", SUBJ("Sensor Technology"), value="solid-state actigraphy sensor"),
        ev("Actigraphy sensor provides body position of patient during sleep.", SEC("Technology"), "context")],
       category="Actigraphy sensor, technology unspecified")
legacy("CLM-32b036c02477", "pos.loc", "inferred (not stated)", "needs clarification",
       "No sentence places the actigraphy sensor. The inference rests on the sensor being 'physically incorporated' in the device, position following the angle of the device, and the recorder being worn on the chest.",
       [ev(ANGLE, COMM("Channels"), value="angle the device is tilted or rotated"),
        ev("The actigraphy sensor was already physically incorporated in ApneaLink Pro.", SUBJ("IEC 60601-1 (Electrical safety)"), "context"),
        ev("The ApneaLink Air recorder and the respiratory effort sensor must be fastened with the re-usable belt on the patient’s chest parallel to the spine.", SEC("Device Description"), "context")],
       interp="inferred", category="Chest (within recorder; inferred)", suggested="Within the recorder worn on the chest (inferred)")
claim("pos.raw", "raw_acquired_signal", "Device tilt/rotation angle", "the angle the device is tilted or rotated",
      evidence=[ev(ANGLE, COMM("Channels"), value="the angle the device is tilted or rotated")],
      interp="normalized", category="Orientation / angle signal",
      note="Comes from the applicant’s comparison commentary (Comments column), not from the subject-device column.")
legacy("CLM-a5dcc1a3a694", "pos.raw.legacy", "misclassified", "reject",
       "'Body position' is the physiological parameter. The acquired quantity stated is the device’s tilt/rotation angle.",
       [ev(ANGLE, COMM("Channels"), "context")], interp="contradicted", superseded=["pos.raw"], aggregate=False)
legacy("CLM-78792476b8f4", "pos.param", "supported, wrong evidence (predicate column)", "verify",
       "The legacy excerpt came from the Nox T3 column. Re-anchored to the subject-column Channels cell.",
       [ev(CH_POS, SUBJ("Channels"), value="body position")], category="Body position")
claim("pos.direct", "direct_vs_derived", "Derived from device orientation (tilt/rotation angle)", "according to the angle the device is tilted or rotated",
      evidence=[ev(ANGLE, COMM("Channels"), value="according to the angle the device is tilted or rotated")],
      interp="normalized", category="Derived")
claim("pos.output", "diagnostic_output", "Not part of the ApneaLink Software report (explicit exclusion)",
      "neither part of the report generated by ApneaLink Software", polarity="negated",
      evidence=[ev(POS_NOT_REPORT, SEC("Technology"), value="neither part of the report"),
                ev("Recorded body position data can be viewed using an EDF viewer but is not displayed in the report generated by the ApneaLink Software.", COMM(INDICES), "context")],
      category="Excluded from report",
      note="Negated claim: the source states that body position is recorded but not reported. It cannot enter Table 8.3 as an output.")
legacy("CLM-030e4da72b91", "pos.feature.legacy", "contradicted", "reject",
       "Body position data are recorded and viewable in an EDF viewer but are explicitly not part of the report. Recorded data is not a reported feature.",
       [ev(POS_NOT_REPORT, SEC("Technology"), "limiting")], interp="contradicted", superseded=["pos.output", "pos.access"], aggregate=False)
claim("pos.access", "signal_access", "Retained and accessible: stored as an EDF+ file on the recorder; readable via USB with an EDF viewer",
      "stored as an EDF+ file on the recorder",
      evidence=[ev(POS_EDF, SEC("Device Description"), value="stored as an EDF+ file")], category="Yes")
claim("pos.valid", "validation_comparator", "Side-by-side testing against Nox T3 using a protractor to show defined positions around the body axis",
      "side by side testing ... using a protractor",
      evidence=[ev("Additional side by side testing has been performed by using a protractor to show the defined position around the body axis for ApneaLink Air and Nox T3.", SEC("Testing summary"))])

# ------------------------------------------------------------------ snoring
claim("sn.param", "physiological_parameter", "Snoring", "snoring",
      evidence=[ev("patient respiratory nasal airflow, snoring, blood oxygen saturation", SEC("Intended Use"), value="snoring")],
      category="Snoring / respiratory sounds")
claim("sn.sensor", "sensor_technology", "Not stated", state="Not stated", interp="not stated",
      absence=["microphone", "acoustic", "sound", "vibration"], category="Sensor not stated",
      note="No snoring sensor is described for the subject device. Snoring may be derived from another channel (for example, nasal pressure), but the summary does not say so.")
claim("sn.loc", "sensor_location", "Not stated", state="Not stated", interp="not stated", category="Not specified",
      note="No snoring sensor is described, so no location is stated.")
claim("sn.raw", "raw_acquired_signal", "Not stated", state="Not stated", interp="not stated", category="Not specified",
      note="No signal source for snoring is described.")
claim("sn.direct", "direct_vs_derived", "Not stated", state="Not stated", interp="not stated", category="Not stated")

# ------------------------------------------------------------------ device-level supplementary
claim("dev.access", "signal_access", "Unclear: recorded data are stored as EDF+ on the SD card and readable over USB as mass storage, but the channels and waveform content are not itemized",
      "Recorded data is stored in European Data Format (EDF+)",
      evidence=[ev(EDF_ALL, SUBJ("Interface between embedded software and PC software/EDF viewer"), value="Recorded data is stored in European Data Format (EDF+)"),
                ev("Data related to patient respiratory nasal airflow, snoring, blood oxygen saturation, pulse, respiratory effort can be transferred to the ApneaLink Software.", SUBJ("Interface between embedded software and PC software/EDF viewer"), "context")],
      interp="normalized", category="Unclear",
      note="Applies to 'recorded data' in general. Whether each waveform is retained and accessible is not stated per channel.")
claim("dev.sampling", "sampling_resolution", "Not stated", state="Not stated", interp="not stated",
      absence=["Hz", "sampling", "sample rate", "resolution", "bits"])
claim("dev.continuity", "continuity", "Not stated", state="Not stated", interp="not stated",
      absence=["continuous", "intermittent", "epoch", "interval"])
claim("dev.sync", "synchronization", "Not stated", state="Not stated", interp="not stated",
      absence=["synchron", "simultaneous", "time-align", "timestamp"])
claim("rep.valid", "validation_comparator", "Event detection and indices not re-tested here: cleared under K083575 (ApneaLink Plus); ApneaLink Pro side-by-side results relied on; comparator not described in this summary",
      "Detection of respiratory events and reported indices was cleared under K083575",
      evidence=[ev("Detection of respiratory events and reported indices was cleared under K083575 (ApneaLink Plus) and remained unchanged in ApneaLink Pro (K131932) and ApneaLink Air.", SEC("Testing summary")),
                ev("Thus side-by-side testing results from ApneaLink Pro comparing detection of all respiratory events remain valid.", SEC("Testing summary"), "context")],
      interp="normalized", note="Cross-reference only. The K083575 document is not used as evidence for this clearance.")

# ------------------------------------------------------------------ report outputs
claim("rep.report", "diagnostic_output", "Report for the HCP generated by the ApneaLink Software", "produce a report for the HCP",
      evidence=[ev("The device uses these recordings to produce a report for the HCP", SEC("Intended Use"), value="produce a report for the HCP"),
                ev("With the ApneaLink Software the physician can generate a report with the recorded and analyzed data (respiratory pressure, respiratory effort, pulse rate, oxygen saturation) to aid in diagnosis.", SEC("Device Description"), "context")],
      category="HCP report")
IDX = [  # legacy id, ref, field, quote, category
    ("CLM-964ea01d51e5", "out.ahi", "AHI", "AHI"),
    ("CLM-2102f8b48d70", "out.ri", "RI", "RI"),
    ("CLM-f2dd379ff37c", "out.ai", "Apnea Index (unclassified, central, mixed, obstructive)", "Apnea index"),
    ("CLM-aeebd6206c8c", "out.hi", "Hypopnea Index", "Hypopnea index"),
    ("CLM-7cdb877b6e99", "feat.flw_nosnore", "Number of flow limited breaths without snoring", "Flow limitation"),
    ("CLM-9bfd0bef8160", "feat.flw_snore", "Number of flow limited breaths with snoring", "Flow limitation with snoring"),
    ("CLM-ac3ad056bb9e", "out.csb", "Cheyne-Stokes Breathing", "Cheyne-Stokes breathing"),
    ("CLM-1cdb0340ac87", "out.odi", "ODI", "ODI"),
    ("CLM-e7ba308a04c1", "feat.sat_avg", "Average saturation", "SpO2 average"),
    ("CLM-5de192f8ed59", "feat.sat_min", "Minimum saturation", "SpO2 minimum"),
    ("CLM-83c2442cfd22", "feat.sat_max", "Maximum saturation", "SpO2 maximum"),
    ("CLM-e1cd3ac8058c", "feat.sat_basal", "Basal saturation", "SpO2 basal"),
    ("CLM-a9ce2d729da8", "feat.pr_min", "Minimum Pulse Rate", "Pulse rate minimum"),
    ("CLM-5a17f0947641", "feat.pr_max", "Maximum Pulse Rate", "Pulse rate maximum"),
    ("CLM-f246d466ecda", "feat.pr_avg", "Average Pulse Rate", "Pulse rate average"),
]
PRED_IDX = {"CLM-964ea01d51e5", "CLM-2102f8b48d70", "CLM-f2dd379ff37c", "CLM-aeebd6206c8c"}
for cid, ref, quote, cat in IDX:
    wrong = cid in PRED_IDX
    legacy(cid, ref, "supported, wrong evidence (predicate column)" if wrong else "supported", "verify",
           ("The legacy excerpt quoted the Noxturnal (Nox T3 predicate) index list. Re-anchored to the merged ApneaLink Pro/ApneaLink Air cell."
            if wrong else "Merged ApneaLink Pro/ApneaLink Air cell; the list applies to the subject device through the column span.")
           + (" 'RI' is not expanded anywhere in the summary." if ref == "out.ri" else "")
           + (" 'ODI' is not expanded, and the parameter it uses is not stated." if ref == "out.odi" else ""),
           [ev(quote, SUBJ(INDICES), value=quote), ev(IDX_LEAD, SUBJ(INDICES), "context")],
           interp="explicit", category=cat)
for sub in ["unclassified", "central", "mixed", "obstructive"]:
    claim(f"out.ai.{sub}", "diagnostic_output", f"Apnea Index, {sub}", sub,
          evidence=[ev("Apnea Index (unclassified, central, mixed, obstructive)", SUBJ(INDICES), value=sub)],
          interp="normalized", category=f"Apnea index ({sub})",
          note="Split from the parenthetical list. The source does not describe how apneas are classified.")

# ------------------------------------------------------------------ chains
M = lambda **k: k
chains = [
    {"chain_id": "CHN-K143272-AIRFLOW", "label": "Nasal pressure → airflow", "summary": "Nasal cannula and solid-state pressure sensor; pressure transformed to flow in the recorder.",
     "slots": M(sensor_technology=["np.cannula", "np.sensor"], sensor_location=["np.loc", "np.sensorloc"], raw_acquired_signal=["np.raw"],
                physiological_parameter=["np.param"], direct_vs_derived=["np.direct"], derived_reported_feature=["feat.flw_nosnore", "feat.flw_snore"],
                diagnostic_output=[], signal_access=["dev.access"], sampling_resolution=["dev.sampling"], continuity=["dev.continuity"], synchronization=["dev.sync"]),
     "caveats": ["Pressure transducer is stated explicitly ('solid-state pressure sensor'); it is not inferred from 'airflow'.",
                 "Signal is not described as a waveform; flow-shape fidelity and bandwidth are not stated."]},
    {"chain_id": "CHN-K143272-EFFORT", "label": "Pneumatic effort sensor → respiratory effort",
     "summary": "Effort channel measured with a pneumatic principle; sensor on the chest.",
     "slots": M(sensor_technology=["eff.sensor"], sensor_location=["eff.loc"], raw_acquired_signal=["eff.raw"], physiological_parameter=["eff.param"],
                direct_vs_derived=["eff.direct"], signal_access=["dev.access"], sampling_resolution=["dev.sampling"], continuity=["dev.continuity"],
                synchronization=["dev.sync"], calibration=["eff.calib"]),
     "caveats": ["Not RIP. RIP appears only in the Nox T3 predicate column.", "No calibration is stated: do not treat as quantitative effort."]},
    {"chain_id": "CHN-K143272-SPO2", "label": "Finger oximetry → SpO2", "summary": "Oximetry sensor on the finger, Nonin Xpod 3012 LP module.",
     "slots": M(sensor_technology=["ox.sensor", "ox.module"], sensor_location=["ox.loc", "ox.modloc"], raw_acquired_signal=["ox.raw"],
                physiological_parameter=["ox.param"], direct_vs_derived=["ox.direct"],
                derived_reported_feature=["feat.sat_avg", "feat.sat_min", "feat.sat_max", "feat.sat_basal"],
                signal_access=["dev.access"], sampling_resolution=["dev.sampling"], continuity=["dev.continuity"], synchronization=["dev.sync"],
                validation_comparator=["ox.valid"]),
     "caveats": ["Raw optical/PPG signal not stated. SpO2 does not imply an accessible PPG waveform."]},
    {"chain_id": "CHN-K143272-PULSE", "label": "Finger oximetry → pulse rate", "summary": "Same oximeter as SpO2.",
     "slots": M(sensor_technology=["ox.sensor", "ox.module"], sensor_location=["ox.loc", "ox.modloc"], raw_acquired_signal=["ox.raw"],
                physiological_parameter=["pr.param"], direct_vs_derived=["ox.direct"],
                derived_reported_feature=["feat.pr_min", "feat.pr_max", "feat.pr_avg"],
                signal_access=["dev.access"], sampling_resolution=["dev.sampling"], continuity=["dev.continuity"], synchronization=["dev.sync"],
                validation_comparator=["ox.valid"]),
     "caveats": ["Pulse rate does not imply an accessible PPG waveform."]},
    {"chain_id": "CHN-K143272-POSITION", "label": "Actigraphy sensor → body position",
     "summary": "Recorded and exportable (EDF+), explicitly not part of the report.",
     "slots": M(sensor_technology=["pos.sensor"], sensor_location=["pos.loc"], raw_acquired_signal=["pos.raw"], physiological_parameter=["pos.param"],
                direct_vs_derived=["pos.direct"], diagnostic_output=["pos.output"], signal_access=["pos.access"], sampling_resolution=["dev.sampling"],
                validation_comparator=["pos.valid"]),
     "caveats": ["Recorded waveform is not a reported output: the source excludes body position from the report.",
                 "Sensor location is inferred, not stated."]},
    {"chain_id": "CHN-K143272-SNORING", "label": "Snoring (sensor not stated)", "summary": "Listed as recorded data. No sensor or signal is described.",
     "slots": M(sensor_technology=["sn.sensor"], sensor_location=["sn.loc"], raw_acquired_signal=["sn.raw"], physiological_parameter=["sn.param"],
                direct_vs_derived=["sn.direct"], derived_reported_feature=["feat.flw_snore", "feat.flw_nosnore"]),
     "caveats": ["Snoring source is not stated: do not assume nasal-pressure-derived snoring."]},
    {"chain_id": "CHN-K143272-REPORT", "kind": "report", "label": "ApneaLink Software report",
     "summary": "Indices generated from the ApneaLink Software. Per-index input signals are not stated.",
     "slots": M(diagnostic_output=["rep.report", "out.ahi", "out.ri", "out.ai", "out.ai.unclassified", "out.ai.central", "out.ai.mixed", "out.ai.obstructive",
                                   "out.hi", "out.csb", "out.odi"],
                derived_reported_feature=["feat.flw_nosnore", "feat.flw_snore", "feat.sat_avg", "feat.sat_min", "feat.sat_max", "feat.sat_basal",
                                          "feat.pr_min", "feat.pr_max", "feat.pr_avg"],
                validation_comparator=["rep.valid"]),
     "caveats": ["AHI is an explicit output here; which signals it uses is not stated.",
                 "Event-detection validation is inherited from K083575 and not re-tested in this submission."]},
]

rels = []
QUOTE_OF = {ref: quote for (_, ref, quote, _) in IDX}
def rel(chain, a, relation, b, basis, evidence=(), note=""):
    if basis == "output-name" and not evidence:
        evidence = [ev(QUOTE_OF[a], SUBJ(INDICES), value=QUOTE_OF[a])]
    rels.append({"chain": chain, "from": a, "relation": relation, "to": b, "basis": basis, "evidence": list(evidence), "note": note})

A = "CHN-K143272-AIRFLOW"
rel(A, "np.cannula", "component_of", "np.sensor", "explicit", [ev("Plastic tubing and cannula for pressure sensing", SUBJ("Method of connection to the Patient"))])
rel(A, "np.cannula", "located_at", "np.loc", "explicit", [ev("The disposable plastic nasal cannula is connected to the ApneaLink Air recorder and fixed at the patient’s nose.", SEC("Device Description"))])
rel(A, "np.sensor", "located_at", "np.sensorloc", "not-stated", note="Transducer location not stated.")
rel(A, "np.sensor", "acquires", "np.raw", "explicit", [ev(ST_PRESS, SUBJ("Sensor Technology")), ev(CH_FLOW, SUBJ("Channels"))])
rel(A, "np.raw", "represents", "np.param", "explicit", [ev("Location of linearization (Transformation of pressure values in flow values)", LABEL("Location of linearization (Transformation of pressure values in flow values)")), ev("ApneaLink Air recorder", SUBJ("Location of linearization (Transformation of pressure values in flow values)"))],
    note="Pressure values are transformed into flow values.")
rel(A, "np.param", "derivation", "np.direct", "explicit", [ev("ApneaLink Air recorder", SUBJ("Location of linearization (Transformation of pressure values in flow values)"))])
for f in ["feat.flw_nosnore", "feat.flw_snore"]:
    rel(A, f, "derived_feature_of", "np.param", "output-name", note="The output name refers to 'flow'. The input signal is not otherwise stated.")
for o in ["out.ahi", "out.ri", "out.ai", "out.hi", "out.csb"]:
    rel(A, o, "reported_as", "np.param", "not-stated", note="Which signals this index uses is not stated in the summary.")

E = "CHN-K143272-EFFORT"
rel(E, "eff.sensor", "located_at", "eff.loc", "explicit", [ev("The ApneaLink Air recorder and the respiratory effort sensor must be fastened with the re-usable belt on the patient’s chest parallel to the spine.", SEC("Device Description"))])
rel(E, "eff.sensor", "acquires", "eff.raw", "explicit", [ev(ST_PRESS, SUBJ("Sensor Technology"))], note="Shared cell: 'for nasal flow and effort'.")
rel(E, "eff.raw", "represents", "eff.param", "explicit", [ev(CH_EFF, SUBJ("Channels"))])
rel(E, "eff.param", "derivation", "eff.direct", "explicit", [ev(CH_EFF, SUBJ("Channels"))])

for C, P in (("CHN-K143272-SPO2", "ox.param"), ("CHN-K143272-PULSE", "pr.param")):
    rel(C, "ox.sensor", "component_of", "ox.module", "explicit", [ev("The oximetry sensor is connected to the Xpod and fixed at the patient’s finger.", SEC("Device Description"))])
    rel(C, "ox.sensor", "located_at", "ox.loc", "explicit", [ev("The oximetry sensor is connected to the Xpod and fixed at the patient’s finger.", SEC("Device Description"))])
    rel(C, "ox.module", "located_at", "ox.modloc", "explicit", [ev("The new low power Xpod is fixed at the belt via clip.", SUBJ("Method of connection to the Patient"))])
    rel(C, "ox.sensor", "acquires", "ox.raw", "not-stated", note="Raw optical signal not stated.")
    rel(C, "ox.sensor", "measures", P, "explicit", [ev(CH_OX, SUBJ("Channels"))], note="The document links oximeter to parameter directly, with no raw-signal description.")
    rel(C, P, "derivation", "ox.direct", "explicit", [ev(CH_OX, SUBJ("Channels"))])
for f in ["feat.sat_avg", "feat.sat_min", "feat.sat_max", "feat.sat_basal"]:
    rel("CHN-K143272-SPO2", f, "derived_feature_of", "ox.param", "output-name", note="The output name refers to 'saturation'.")
rel("CHN-K143272-SPO2", "out.odi", "reported_as", "ox.param", "not-stated", note="'ODI' is not expanded, and its input is not stated.")
for f in ["feat.pr_min", "feat.pr_max", "feat.pr_avg"]:
    rel("CHN-K143272-PULSE", f, "derived_feature_of", "pr.param", "output-name", note="The output name refers to 'Pulse Rate'.")

Pn = "CHN-K143272-POSITION"
rel(Pn, "pos.sensor", "measures", "pos.param", "explicit", [ev("Actigraphy sensor provides body position of patient during sleep.", SEC("Technology"))])
rel(Pn, "pos.sensor", "located_at", "pos.loc", "inferred", [ev(ANGLE, COMM("Channels")), ev("The actigraphy sensor was already physically incorporated in ApneaLink Pro.", SUBJ("IEC 60601-1 (Electrical safety)"))])
rel(Pn, "pos.sensor", "acquires", "pos.raw", "inferred", [ev(ANGLE, COMM("Channels"))], note="The sensor is assumed to report the device’s angle; the source ties position to the device’s angle, not to the sensor.")
rel(Pn, "pos.raw", "represents", "pos.param", "explicit", [ev(ANGLE, COMM("Channels"))])
rel(Pn, "pos.param", "derivation", "pos.direct", "explicit", [ev(ANGLE, COMM("Channels"))])
rel(Pn, "pos.output", "reported_as", "pos.param", "explicit", [ev(POS_NOT_REPORT, SEC("Technology"))], note="Negated: explicitly not reported.")

S = "CHN-K143272-SNORING"
rel(S, "sn.sensor", "measures", "sn.param", "not-stated", note="No snoring sensor described.")
rel(S, "sn.sensor", "located_at", "sn.loc", "not-stated")
rel(S, "sn.sensor", "acquires", "sn.raw", "not-stated")
rel(S, "sn.param", "derivation", "sn.direct", "not-stated")
for f in ["feat.flw_snore", "feat.flw_nosnore"]:
    rel(S, f, "derived_feature_of", "sn.param", "output-name", note="The output name refers to snoring.")

R = "CHN-K143272-REPORT"
for o in ["out.ahi", "out.ri", "out.ai", "out.hi", "out.csb", "out.odi", "feat.flw_nosnore", "feat.flw_snore", "feat.sat_avg", "feat.sat_min",
          "feat.sat_max", "feat.sat_basal", "feat.pr_min", "feat.pr_max", "feat.pr_avg"]:
    rel(R, o, "generated_by", "rep.report", "explicit", [ev(IDX_LEAD, SUBJ(INDICES)), ev(IN_REPORT, COMM(INDICES))])
for sub in ["unclassified", "central", "mixed", "obstructive"]:
    rel(R, f"out.ai.{sub}", "generated_by", "rep.report", "explicit", [ev("Apnea Index (unclassified, central, mixed, obstructive)", SUBJ(INDICES))])

out = {
    "k_number": "K143272",
    "curator": "Claude (claude-opus-5-5), prototype curation draft",
    "curated_on": "2026-09-24",
    "status": "Curator proposals only. No claim or relationship in this file is human-reviewed; every review_decision stays pending.",
    "scope_note": "Uses only the K143272 FDA PDF. Predicate columns are used only as limiting or contrasting evidence. No manufacturer labeling, predicate documents, or general device knowledge.",
    "legacy_assessments": assess, "claims": claims, "chains": chains, "relationships": rels,
}
json.dump(out, open(sys.argv[1], "w"), ensure_ascii=False, indent=1)
print(len(assess), "assessments", len(claims), "new claims", len(chains), "chains", len(rels), "relationships")
